packages:
  - apps/*
  - backend
  - packages/*
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - electron-winstaller
  - electron
  - esbuild
  - prisma
  - unrs-resolver
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  electron: true
  electron-winstaller: true
  esbuild: true
  prisma: true
  unrs-resolver: true
