import type { CampoPlantilla } from "@flowsort/shared";
const extra:CampoPlantilla={id:"especificaciones_adicionales",etiqueta:"Especificaciones adicionales",tipo:"textarea",requerido:false};
const f=(id:string,etiqueta:string,tipo:CampoPlantilla["tipo"]="texto",requerido=false,opciones?:string[]):CampoPlantilla=>({id,etiqueta,tipo,requerido,...(opciones?{opciones}:{})});
export const PLANTILLAS_SEED=[
  {nombre:"General",descripcion:"Registro general",esDefault:true,campos:[f("especificaciones","Especificaciones del cliente","textarea"),extra]},
  {nombre:"Restaurante",campos:[f("reserva","Número de mesa/reserva"),f("comensales","Cantidad de comensales","numero",true),f("fecha_hora","Fecha y hora de reserva","fecha_hora",true),f("alergias","Alergias/restricciones","textarea"),f("ocasion","Ocasión especial","select",false,["Cumpleaños","Aniversario","Negocios","Otra"]),f("notas","Notas","textarea"),extra]},
  {nombre:"Clínica / Hospital",campos:[f("motivo","Motivo de consulta","textarea",true),f("medico","Médico asignado"),f("historia","Número de historia clínica"),f("seguro","Tipo de seguro"),f("sintomas","Síntomas","textarea"),f("cita","Fecha y hora de la cita","fecha_hora",true),extra]},
  {nombre:"Agencia de viajes",campos:[f("destino","Destino","texto",true),f("salida","Fecha de salida","fecha"),f("retorno","Fecha de retorno","fecha"),f("pasajeros","Número de pasajeros","numero"),f("paquete","Tipo de paquete","select",false,["Básico","Estándar","Premium"]),f("presupuesto","Presupuesto estimado","numero"),f("preferencias","Preferencias","textarea"),extra]},
  {nombre:"Hotel / Alojamiento",campos:[f("check_in","Check-in","fecha",true),f("check_out","Check-out","fecha",true),f("habitacion","Tipo de habitación","select",false,["Individual","Doble","Suite"]),f("huespedes","Número de huéspedes","numero"),f("requerimientos","Requerimientos especiales","textarea"),extra]},
  {nombre:"Taller automotriz",campos:[f("vehiculo","Marca y modelo","texto",true),f("placa","Placa"),f("motivo","Motivo del servicio","textarea",true),f("kilometraje","Kilometraje","numero"),f("entrega","Fecha estimada de entrega","fecha"),extra]},
  {nombre:"Inmobiliaria",campos:[f("propiedad","Tipo de propiedad","select",false,["Casa","Departamento","Terreno","Comercial"]),f("presupuesto","Presupuesto máximo","numero"),f("zona","Zona de interés"),f("finalidad","Finalidad","select",false,["Compra","Alquiler","Inversión"]),f("notas","Notas","textarea"),extra]},
  {nombre:"Gimnasio",campos:[f("objetivo","Objetivo del cliente","select",false,["Fuerza","Pérdida de peso","Resistencia","Bienestar"]),f("plan","Plan de interés"),f("condicion","Condición médica relevante","textarea"),f("horario","Horario preferido"),extra]},
  {nombre:"Salón de belleza / Spa",campos:[f("servicio","Servicio solicitado","texto",true),f("especialista","Especialista preferido"),f("fecha_hora","Fecha y hora deseada","fecha_hora"),f("alergias","Alergias a productos","textarea"),extra]},
  {nombre:"Bufete legal",campos:[f("caso","Tipo de caso","select",false,["Civil","Penal","Laboral","Mercantil","Familiar"]),f("descripcion","Descripción breve","textarea",true),f("abogado","Abogado asignado"),f("urgencia","Urgencia del trámite"),extra]},
  {nombre:"Servicio técnico / Reparaciones",campos:[f("equipo","Equipo/dispositivo","texto",true),f("falla","Falla reportada","textarea",true),f("recepcion","Fecha de recepción","fecha"),f("garantia","Garantía vigente","checkbox"),extra]}
];
