import { Pool } from "pg";import { Prisma,PrismaClient as TenantPrisma } from "../generated/tenant/index.js";import { controlDb } from "../db/control.js";import { env } from "../config/env.js";import { descifrarSecreto } from "./crypto.js";import { PLANTILLAS_SEED } from "./templates.js";
const clientes=new Map<string,{client:TenantPrisma;usado:number}>();const MAX_CLIENTES=50;
function urlConSchema(base:string,schema:string){const u=new URL(base);u.searchParams.set("schema",schema);return u.toString();}
function validarSchema(schema:string){if(!/^[a-z][a-z0-9_]{0,62}$/.test(schema))throw new Error("Schema tenant inválido");return `"${schema}"`;}
export async function provisionarTenant(baseUrl:string,schema:string,plantillaPreferida?:string){const q=validarSchema(schema);const pool=new Pool({connectionString:baseUrl,max:1});const c=await pool.connect();try{await c.query("BEGIN");await c.query(`CREATE SCHEMA IF NOT EXISTS ${q}`);await c.query(`DO $$ BEGIN CREATE TYPE ${q}.\"Prioridad\" AS ENUM ('BAJA','PREDETERMINADA','ALTA','SUPER_ALTA'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`);await c.query(`DO $$ BEGIN CREATE TYPE ${q}.\"EstadoRegistro\" AS ENUM ('PENDIENTE','EN_PROCESO','COMPLETADO'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`);await c.query(`CREATE TABLE IF NOT EXISTS ${q}.\"Plantilla\" (\"id\" UUID PRIMARY KEY DEFAULT gen_random_uuid(),\"nombre\" TEXT NOT NULL UNIQUE,\"descripcion\" TEXT,\"esDefault\" BOOLEAN NOT NULL DEFAULT false,\"campos\" JSONB NOT NULL)`);await c.query(`CREATE TABLE IF NOT EXISTS ${q}.\"Registro\" (\"id\" UUID PRIMARY KEY DEFAULT gen_random_uuid(),\"nombreCliente\" TEXT NOT NULL,\"contacto\" TEXT,\"plantillaId\" UUID NOT NULL REFERENCES ${q}.\"Plantilla\"(\"id\"),\"especificaciones\" JSONB NOT NULL,\"prioridad\" ${q}.\"Prioridad\" NOT NULL DEFAULT 'PREDETERMINADA',\"estado\" ${q}.\"EstadoRegistro\" NOT NULL DEFAULT 'PENDIENTE',\"usuarioId\" UUID NOT NULL,\"fechaRegistro\" TIMESTAMPTZ NOT NULL DEFAULT now(),\"fechaActualizacion\" TIMESTAMPTZ NOT NULL DEFAULT now())`);for(const col of ["prioridad","fechaRegistro","plantillaId","usuarioId"])await c.query(`CREATE INDEX IF NOT EXISTS \"Registro_${col}_idx\" ON ${q}.\"Registro\"(\"${col}\")`);await c.query("COMMIT");}catch(e){await c.query("ROLLBACK");throw e}finally{c.release();await pool.end();}
  const db=new TenantPrisma({datasourceUrl:urlConSchema(baseUrl,schema)});await db.plantilla.createMany({data:PLANTILLAS_SEED.map(p=>({...p,esDefault:plantillaPreferida?p.nombre===plantillaPreferida:p.esDefault,campos:p.campos as unknown as Prisma.InputJsonValue})),skipDuplicates:true});await db.$disconnect();
}
async function conexionEmpresa(empresaId:string){const e=await controlDb.empresa.findUniqueOrThrow({where:{id:empresaId}});if(!e.schemaTenant)throw new Error("Schema tenant ausente");if(e.modoHostingDB==="AUTOALOJADO"){if(!e.conexionCifrada)throw new Error("Conexión autoalojada no configurada");return {url:await descifrarSecreto(e.conexionCifrada),schema:e.schemaTenant};}return {url:env.MANAGED_DATABASE_URL,schema:e.schemaTenant};}
export async function tenantDb(empresaId:string){const actual=clientes.get(empresaId);if(actual){actual.usado=Date.now();return actual.client}const {url,schema}=await conexionEmpresa(empresaId);const client=new TenantPrisma({datasourceUrl:urlConSchema(url,schema)});clientes.set(empresaId,{client,usado:Date.now()});if(clientes.size>MAX_CLIENTES){const [id,v]=[...clientes].sort((a,b)=>a[1].usado-b[1].usado)[0];clientes.delete(id);void v.client.$disconnect();}return client;}
export async function invalidarTenant(empresaId:string){const v=clientes.get(empresaId);if(v){clientes.delete(empresaId);await v.client.$disconnect();}}
