import { Router } from "express";import { z } from "zod";import { validarEspecificaciones,type CampoPlantilla,sugerirPrioridad } from "@flowsort/shared";import { Prisma } from "../generated/tenant/index.js";import { tenantDb } from "../services/tenant.js";import { ruta } from "../utils/async-route.js";
const router=Router();const prioridad=z.enum(["BAJA","PREDETERMINADA","ALTA","SUPER_ALTA"]);const estado=z.enum(["PENDIENTE","EN_PROCESO","COMPLETADO"]);const idSchema=z.string().uuid();const payload=z.object({nombreCliente:z.string().trim().min(1).max(200),contacto:z.string().max(200).nullable().optional(),plantillaId:z.string().uuid(),especificaciones:z.record(z.unknown()),prioridad:prioridad.default("PREDETERMINADA"),estado:estado.default("PENDIENTE")});
export const filtrosSchema=z.object({prioridad:prioridad.optional(),plantillaId:z.string().uuid().optional(),estado:estado.optional(),busqueda:z.string().max(100).optional(),usuarioId:z.string().uuid().optional(),desde:z.coerce.date().optional(),hasta:z.coerce.date().optional(),pagina:z.coerce.number().int().positive().default(1),limite:z.coerce.number().int().min(1).max(100).default(25)});
export function crearWhere(f:z.infer<typeof filtrosSchema>):Prisma.RegistroWhereInput{return { ...(f.prioridad&&{prioridad:f.prioridad}),...(f.plantillaId&&{plantillaId:f.plantillaId}),...(f.estado&&{estado:f.estado}),...(f.usuarioId&&{usuarioId:f.usuarioId}),...(f.busqueda&&{OR:[{nombreCliente:{contains:f.busqueda,mode:"insensitive"}},{contacto:{contains:f.busqueda,mode:"insensitive"}}]}),...((f.desde||f.hasta)&&{fechaRegistro:{...(f.desde&&{gte:f.desde}),...(f.hasta&&{lte:f.hasta})}})};}
async function plantillaValida(db:Awaited<ReturnType<typeof tenantDb>>,plantillaId:string,datos:unknown){const p=await db.plantilla.findUnique({where:{id:plantillaId}});if(!p)return {error:"Plantilla no encontrada"};const v=validarEspecificaciones(p.campos as unknown as CampoPlantilla[],datos);return v.success?{}:{error:"Especificaciones inválidas",detalles:v.error.flatten()};}
router.get("/",ruta(async(req,res)=>{const f=filtrosSchema.parse(req.query),db=await tenantDb(req.auth!.empresaId),where=crearWhere(f);const [total,items]=await db.$transaction([db.registro.count({where}),db.registro.findMany({where,include:{plantilla:{select:{id:true,nombre:true,campos:true}}},orderBy:[{prioridad:"desc"},{fechaRegistro:"asc"}],skip:(f.pagina-1)*f.limite,take:f.limite})]);res.json({items,total,pagina:f.pagina,paginas:Math.ceil(total/f.limite)})}));
router.post("/",ruta(async(req,res)=>{const d=payload.parse(req.body),db=await tenantDb(req.auth!.empresaId),v=await plantillaValida(db,d.plantillaId,d.especificaciones);if(v.error)return res.status(400).json(v);const prioridad=d.prioridad==="PREDETERMINADA"?sugerirPrioridad(`${d.nombreCliente} ${JSON.stringify(d.especificaciones)}`):d.prioridad;const r=await db.registro.create({data:{...d,prioridad,especificaciones:d.especificaciones as Prisma.InputJsonValue,usuarioId:req.auth!.sub}});res.status(201).json(r)}));
router.put("/:id",ruta(async(req,res)=>{const id=idSchema.parse(req.params.id),d=payload.parse(req.body),db=await tenantDb(req.auth!.empresaId),v=await plantillaValida(db,d.plantillaId,d.especificaciones);if(v.error)return res.status(400).json(v);const existe=await db.registro.findUnique({where:{id}});if(!existe)return res.status(404).json({error:"Registro no encontrado"});res.json(await db.registro.update({where:{id},data:{...d,especificaciones:d.especificaciones as Prisma.InputJsonValue}}))}));
router.delete("/:id",ruta(async(req,res)=>{const id=idSchema.parse(req.params.id),db=await tenantDb(req.auth!.empresaId);const r=await db.registro.deleteMany({where:{id}});if(!r.count)return res.status(404).json({error:"Registro no encontrado"});res.status(204).end()}));export default router;
